[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://qmhcoafhjudcwazarzui.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaGNvYWZoanVkY3dhemFyenVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTIwMzksImV4cCI6MjA3Mzg2ODAzOX0.0P_-BwxFpaudjZnWjTJsa8L15Fi8zi7r6DVBxzDfUxM"
  OPENAI_API_KEY = "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"
  OPENAI_WEBHOOK_SECRET = "your_webhook_secret_here"
  OPENAI_PROJECT_ID = "proj_your_project_id_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200